-- Member identity, likes, and comments for the TrackPro community board.

alter table public.community_posts
  add column if not exists user_id uuid references public.profiles(id) on delete set null;

create table if not exists public.community_post_likes (
  id bigint generated by default as identity primary key,
  post_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint community_post_likes_unique unique (post_id, user_id)
);

create table if not exists public.community_post_comments (
  id bigint generated by default as identity primary key,
  post_id text not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  author_name text not null check (char_length(trim(author_name)) between 1 and 200),
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists community_post_likes_post_id_idx
  on public.community_post_likes(post_id);

create index if not exists community_post_comments_post_id_created_idx
  on public.community_post_comments(post_id, created_at);

alter table public.community_post_likes enable row level security;
alter table public.community_post_comments enable row level security;

grant select on public.community_post_likes to anon, authenticated;
grant select on public.community_post_comments to anon, authenticated;
grant insert, delete on public.community_post_likes to authenticated;
grant insert, delete on public.community_post_comments to authenticated;
grant usage, select on sequence public.community_post_likes_id_seq to authenticated;
grant usage, select on sequence public.community_post_comments_id_seq to authenticated;

drop policy if exists "community_likes_public_read" on public.community_post_likes;
create policy "community_likes_public_read" on public.community_post_likes
for select to anon, authenticated
using (true);

drop policy if exists "community_members_add_own_like" on public.community_post_likes;
create policy "community_members_add_own_like" on public.community_post_likes
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "community_members_remove_own_like" on public.community_post_likes;
create policy "community_members_remove_own_like" on public.community_post_likes
for delete to authenticated
using (auth.uid() = user_id or public.is_admin());

drop policy if exists "community_comments_public_read" on public.community_post_comments;
create policy "community_comments_public_read" on public.community_post_comments
for select to anon, authenticated
using (true);

drop policy if exists "community_members_add_own_comment" on public.community_post_comments;
create policy "community_members_add_own_comment" on public.community_post_comments
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "community_members_remove_own_comment" on public.community_post_comments;
create policy "community_members_remove_own_comment" on public.community_post_comments
for delete to authenticated
using (auth.uid() = user_id or public.is_admin());

create or replace function public.cleanup_community_post_engagement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.community_post_likes where post_id = old.id::text;
  delete from public.community_post_comments where post_id = old.id::text;
  return old;
end;
$$;

drop trigger if exists cleanup_community_post_engagement_trigger on public.community_posts;
create trigger cleanup_community_post_engagement_trigger
before delete on public.community_posts
for each row execute function public.cleanup_community_post_engagement();

comment on table public.community_post_likes is
  'One like per authenticated TrackPro member and community post.';

comment on table public.community_post_comments is
  'Comments written by authenticated TrackPro members on community posts.';

notify pgrst, 'reload schema';
